name: LaTeX build and deploy

on:
  push:
    branches:
      - main  # Run the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Run the workflow on pull requests to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: danteev/texlive:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List directory contents
      run: |
        ls -R report

    - name: Compile LaTeX document
      run: |
        cd report
        pdflatex -interaction=nonstopmode -halt-on-error main.tex
        biber main
        pdflatex -interaction=nonstopmode -halt-on-error main.tex
        pdflatex -interaction=nonstopmode -halt-on-error main.tex

    - name: Move PDF to root
      run: mv report/main.pdf ./main.pdf

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add main.pdf
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update compiled PDF" && git push)

    - name: Upload compiled PDF as artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdf
        path: main.pdf
